# Generated by Django 3.0.3 on 2020-07-17 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elder_gurder_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
